# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/cloakdf',
                'doc_host': 'https://giordafrancis.github.io',
                'git_url': 'https://github.com/giordafrancis/cloakdf',
                'lib_path': 'cloakdf'},
  'syms': { 'cloakdf.core': { 'cloakdf.core.CloakDF': ('core.html#cloakdf', 'cloakdf/core.py'),
                              'cloakdf.core.CloakDF.__init__': ('core.html#cloakdf.__init__', 'cloakdf/core.py'),
                              'cloakdf.core.CloakDF._mask_columns': ('core.html#cloakdf._mask_columns', 'cloakdf/core.py'),
                              'cloakdf.core.CloakDF._pseudonymise_keys': ('core.html#cloakdf._pseudonymise_keys', 'cloakdf/core.py'),
                              'cloakdf.core.CloakDF._remap': ('core.html#cloakdf._remap', 'cloakdf/core.py'),
                              'cloakdf.core.CloakDF.decode': ('core.html#cloakdf.decode', 'cloakdf/core.py'),
                              'cloakdf.core.CloakDF.encode': ('core.html#cloakdf.encode', 'cloakdf/core.py'),
                              'cloakdf.core.CloakDF.generate_key': ('core.html#cloakdf.generate_key', 'cloakdf/core.py'),
                              'cloakdf.core.CloakDF.load': ('core.html#cloakdf.load', 'cloakdf/core.py'),
                              'cloakdf.core.CloakDF.load_key': ('core.html#cloakdf.load_key', 'cloakdf/core.py'),
                              'cloakdf.core.CloakDF.save': ('core.html#cloakdf.save', 'cloakdf/core.py')}}}
