"""`core` contains the `CloakDF` class — a pseudonymisation/anonymisation engine for consistent cross-table key replacement and column masking, with Fernet-encrypted storage of mappings."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['CloakDF']

# %% ../nbs/00_core.ipynb #6236927c
import uuid, json
from pathlib import Path
from cryptography.fernet import Fernet
import pandas as pd


class CloakDF:
    """Pseudonymise and mask DataFrames consistently across related tables."""
    def __init__(self, tables):
        self.tables,self.vault,self.key_maps = tables,{},{}

    def encode(self, name, df):
        """Pseudonymise keys and mask columns for table `name`, returning new DataFrame."""
        df = self._pseudonymise_keys(name, df)
        return self._mask_columns(name, df)

    def decode(self, name, df):
        """Reverse `encode` — restore original keys and masked values."""
        df = df.copy()
        tbl = self.tables[name]
        ids = {k: v for k, v in tbl.items() if k.startswith('id')}
        for group, col in ids.items():
            inv = {v: k for k, v in self.key_maps[group].items()}
            df[col] = df[col].map(inv)
        inv_vault = {v: k for k, v in self.vault.items()}
        for col in tbl.get('mask', []):
            df[col] = df[col].map(inv_vault)
        return df

    def _remap(self, df, col, mapping, id_fn):
        """Replace `col` values via `mapping`, adding new entries with `id_fn`."""
        for val in df[col].dropna().unique():
            mapping.setdefault(str(val), id_fn())
        df[col] = df[col].astype(str).map(mapping)
        return df

    def _pseudonymise_keys(self, name, df):
        """Replace id columns with consistent UUIDs via `key_maps`."""
        df = df.copy()
        tbl = self.tables[name]
        ids = {k: v for k, v in tbl.items() if k.startswith('id')}
        for group, col in ids.items():
            assert df[col].notna().all(), f"Null found in {col} for table {name}"
            assert pd.api.types.is_string_dtype(df[col]), f"Column {col} must be string type, got {df[col].dtype}"
            km = self.key_maps.setdefault(group, {})
            df = self._remap(df, col, km, lambda: str(uuid.uuid4()))
        return df

    def _mask_columns(self, name, df):
        """Replace mask columns with truncated hex tokens via shared `vault`."""
        tbl = self.tables[name]
        for col in tbl.get('mask', []):
            df = self._remap(df, col, self.vault, lambda: uuid.uuid4().hex[:12])
        return df

    def save(self, path, key):
        """Encrypt and save `key_maps` + `vault` to `path` using Fernet `key`."""
        data = json.dumps({'key_maps': self.key_maps, 'vault': self.vault})
        Path(path).write_bytes(Fernet(key).encrypt(data.encode()))

    @classmethod
    def load(cls, path, key, tables):
        """Load encrypted mappings from `path` and return a new `CloakDF` instance."""
        data = json.loads(Fernet(key).decrypt(Path(path).read_bytes()))
        unk = cls(tables)
        unk.key_maps, unk.vault = data['key_maps'], data['vault']
        return unk

    @staticmethod
    def generate_key(path=None):
        """Generate a Fernet key, optionally saving to `path`."""
        key = Fernet.generate_key()
        if path: Path(path).write_bytes(key)
        return key

    @staticmethod
    def load_key(path=None, env_var=None):
        """Load a Fernet key from `path` or `env_var`."""
        if path: return Path(path).read_bytes()
        if env_var:
            import os
            return os.environ[env_var].encode()
        raise ValueError("Provide either path or env_var")
