# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/unknown',
                'doc_host': 'https://frangs.github.io',
                'git_url': 'https://github.com/frangs/unknown',
                'lib_path': 'unknown'},
  'syms': {'unknown.core': {'unknown.core.foo': ('core.html#foo', 'unknown/core.py')}}}
