# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/unknown',
                'doc_host': 'https://frangs.github.io',
                'git_url': 'https://github.com/frangs/unknown',
                'lib_path': 'unknown'},
  'syms': { 'unknown.core': { 'unknown.core.Unknown': ('core.html#unknown', 'unknown/core.py'),
                              'unknown.core.Unknown.__init__': ('core.html#unknown.__init__', 'unknown/core.py'),
                              'unknown.core.Unknown._mask_columns': ('core.html#unknown._mask_columns', 'unknown/core.py'),
                              'unknown.core.Unknown._pseudonymise_keys': ('core.html#unknown._pseudonymise_keys', 'unknown/core.py'),
                              'unknown.core.Unknown._remap': ('core.html#unknown._remap', 'unknown/core.py'),
                              'unknown.core.Unknown.decode': ('core.html#unknown.decode', 'unknown/core.py'),
                              'unknown.core.Unknown.encode': ('core.html#unknown.encode', 'unknown/core.py'),
                              'unknown.core.Unknown.generate_key': ('core.html#unknown.generate_key', 'unknown/core.py'),
                              'unknown.core.Unknown.load': ('core.html#unknown.load', 'unknown/core.py'),
                              'unknown.core.Unknown.load_key': ('core.html#unknown.load_key', 'unknown/core.py'),
                              'unknown.core.Unknown.save': ('core.html#unknown.save', 'unknown/core.py')}}}
